### ISSUE TITLE
Timeout on connection error

### ISSUE THREAD

**Issue by col-panic** [phwiget/ebox-elexis#1]
There currently seems to be no timeout message in case of a connection error or wrong connection configuration!

**Comment by phwiget** [comment]
Agree that the error handling could be improved:
-  Is there any standard format for errors in FHIR?

Currently everything that is not a `200` or `201` will be treated as a general error (see <https://github.com/phwiget/ebox-elexis/blob/master/app/utils/WebService.scala>)

**Comment by col-panic** [comment]
I'm trying to get it up and running - only seeing the spinner .. FHIR is reachable on localhost, authentication is deactivated - what am i doing wrong ?? skype ?? :)

**Comment by phwiget** [comment]
sure, give me 5 minutes
