### ISSUE TITLE
Provide configurable value for ES connection

### ISSUE THREAD

**Issue by col-panic** [phwiget/ebox-elexis#5]
Currently the connection to Elexis Server is fixed to localhost:8380, could you please provide a possibility for this to be configurable? Best via a parameter with activator run or something!

thanks :)

**Comment by phwiget** [comment]
in /conf/application.conf

```
application.elexis.server.port = "8380"
application.elexis.server.baseUrl = "http://localhost"
```

If you omit it, default values apply.

**Comment by phwiget** [comment]
BTW, you can override some config values in the activator or use a separate config:
<https://www.playframework.com/documentation/2.5.x/ProductionConfiguration>

**Comment by col-panic** [comment]
Thanks a lot! I'll give it a try :)
