### ISSUE TITLE
Show connection status and information

### ISSUE THREAD

**Issue by col-panic** [phwiget/ebox-elexis#6]
Please add a hint or information somewhere, wether the connection to FHIR is ok, and what connection url is used! Would help me a lot in debugging :)

thanks a lot!!

**Comment by phwiget** [comment]
Added a logger in case of a server error (HTTP STATUS=500)
In general: there is no permanent connection, only per request as this is based on HTTP. You will get different errors based on the status of the HTTP response:

- 4XX: Error that the server sent. In this case, the connection is fine
- 5XX: Server is not available -> new logger will output the URI requested to the standard output, i.e.
`Server unavailable on http://localhost:8380/fhir/Patient?name=asdf`

**Comment by col-panic** [comment]
Thanks a lot! I see it works with untouched configuration, but does it still work when starting with parameter like -Dapplication.elexis.server.baseUrl=http://elexisserver ?? It seems like I can't get a connection, yet no error message is shown?!

**Comment by col-panic** [comment]
The case seems to be that port 8380 could generally be connected, but that the FHIR service was not installed, and henced did not react. Does the  output consider this?

**Comment by phwiget** [comment]
What do you mean exactly...? On which URL is the FHIR running?

**Comment by col-panic** [comment]
http://elexisserver:8380/fhir (intra docker container link)

**Comment by phwiget** [comment]
when i do 
`$ activator -Dapplication.elexis.server.baseUrl=http://elexisserver`
`$ run`

I will get
`[error] application - Server unavailable on http://elexisserver:8380/fhir/Patient?name=asdf`
So the url is constructed correctly and error logging seems to work. Don't you get any message? Then it should work.

You may can debug FHIR errors in the console of the browser. The app will simply forward errors from FHIR to the frontend.

**Comment by phwiget** [comment]
![grafik](https://user-images.githubusercontent.com/5910761/28516547-e4eb7fb8-7061-11e7-8154-17b721e4c503.png)

**Comment by phwiget** [comment]
(Bad example, as this is the standard error in case the FHIR cannot be accessed. Anyway, normally there would be errors from FHIR if FHIR can be accessed)

**Comment by col-panic** [comment]
In the case the server is generelly available, but the FHIR plugin is not installed, a request to 
http://elexisserver:8380/fhir/Patient?name=asdf is answered with 404 - does this lead to a log output??

**Comment by phwiget** [comment]
The error is now also logged to the standard output for Status 400 errors:(ae77f24ae13ecaedf60c39a733216b33f3f4d266)
